<a href="https://colab.research.google.com/github/ssp1989/DTC/blob/main/NUMPY_ARRAY(16_12_2022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np.arange(1,2)

array([1])

In [ ]:
np.random.rand(20)

array([0.56593473, 0.86512737, 0.12672808, 0.73581463, 0.00444989,
       0.30416872, 0.73839421, 0.30064497, 0.41974279, 0.21735529,
       0.92403162, 0.23440008, 0.09436489, 0.50147773, 0.31824566,
       0.60340694, 0.45955852, 0.89663444, 0.20916393, 0.59547354])

In [ ]:
np.random.randint(1,5,10)

array([1, 2, 4, 4, 4, 2, 2, 2, 1, 4])

In [ ]:
arr.reshape(5,5)

NameError: ignored

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(1,10,2)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([6, 9])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(4,4)

ValueError: ignored

In [ ]:
arr = np.arange(36)

In [ ]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
arr = np.arange(49)

In [ ]:
arr.reshape(7,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [ ]:
arr = np.arange(81)

In [ ]:
arr.reshape(9,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [ ]:
ranarr

array([6, 9])

In [ ]:
ranarr = np.random.randint(1,10,7)

In [ ]:
ranarr

array([1, 7])

In [ ]:
ranarr

array([97,  4, 81,  1, 69, 17, 39, 18, 98, 89])

In [ ]:
ranarr.min()

1

In [ ]:
ranarr.max()

98

In [ ]:
ranarr.argmin()

3

In [ ]:
ranarr.argmax()

8

In [ ]:
ranarr.argmin()

5

In [ ]:
# ASSIGNMENT

In [ ]:
arr = np.arange(0,100,2)

In [ ]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
arr = np.arange(0,100,3)

In [ ]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
arr = np.arange(0,300,2)

In [ ]:
arr

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298])

In [ ]:
arr = np.arange(0,300,3)

In [ ]:
arr

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228, 231,
       234, 237, 240, 243, 246, 249, 252, 255, 258, 261, 264, 267, 270,
       273, 276, 279, 282, 285, 288, 291, 294, 297])

In [ ]:
arr = np.arange(0,-100,-2)

In [ ]:
arr

array([  0,  -2,  -4,  -6,  -8, -10, -12, -14, -16, -18, -20, -22, -24,
       -26, -28, -30, -32, -34, -36, -38, -40, -42, -44, -46, -48, -50,
       -52, -54, -56, -58, -60, -62, -64, -66, -68, -70, -72, -74, -76,
       -78, -80, -82, -84, -86, -88, -90, -92, -94, -96, -98])

In [ ]:
print('The following numbers are even numbers')
x = np.arange(0,100,2)
print(x)

The following numbers are even numbers
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [ ]:
print('the follwoing numbers are odd numbers')
x = np.arange(0,100,3)
print(x)

the follwoing numbers are odd numbers
[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]
