<a href="https://colab.research.google.com/github/ssp1989/DTC/blob/main/Numpy_Assignment(19_12_2022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Numpy commands Learned Till Date

In [2]:
import numpy as np

In [3]:
np.arange(0,15)   # array with range 0 to 15 / 15 = n-1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
np.arange(0,20,2) # array with range 0 to 20 and with +2 increment (possibly even numbers) / 20 = n-1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
np.zeros(2) # array in single row vector with two elements of zeros

array([0., 0.])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(5) # array in single row vector with five elements of ones

array([1., 1., 1., 1., 1.])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.zeros((3,3)) # array in 3 by 3 matrix (3 rows and 3 columns) with the elements of zeros  NOTE : the command shoul have two brackets

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,5)) #array in 3 by 5 matrix (3rows and 5 columns) with the elements of ones NOTE: the command should have two brackets

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.eye(4,4) # it is a array in 4 by 4 identical matrix NOTE : eye command is for identical matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(5,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
#random

In [18]:
np.random.rand(10) # it is array of random values of 10 elements

array([0.90597138, 0.19506051, 0.15253137, 0.71449989, 0.33810203,
       0.33688154, 0.8490899 , 0.48716214, 0.9264994 , 0.83370889])

In [19]:
np.random.rand(5)

array([0.60599725, 0.69130638, 0.47606571, 0.64003675, 0.88450285])

In [21]:
np.random.rand(1,2) # random value of one row with two elemenets

array([[0.49528428, 0.77064008]])

In [22]:
np.random.rand(1,10,2)

array([[[0.16172464, 0.54677965],
        [0.85658374, 0.30263106],
        [0.12872653, 0.08687869],
        [0.93429732, 0.3070612 ],
        [0.29974696, 0.87262143],
        [0.339183  , 0.02965211],
        [0.7899222 , 0.59822217],
        [0.96357491, 0.94031389],
        [0.24759425, 0.0250526 ],
        [0.44500211, 0.95251894]]])

In [2]:
import numpy as np

In [3]:
np.random.randint(3,5)

3

In [4]:
np.random.randint(1,10) # shows the random value between 1 to 10

9

In [5]:
np.random.randint(1,20,2) #shows the 2 random value between 1 to 20

array([18,  4])

In [7]:
np.random.randint(15,30,2)

array([21, 19])

In [8]:
# ARRAYS

In [9]:
arr = np.arange(30)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [12]:
arr = np.arange(81)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [14]:
arr.reshape(9,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])

In [15]:
arr.shape

(81,)

In [16]:
ranarr = np.random.randint(1,50,5)

In [17]:
ranarr

array([31,  7, 26, 30, 10])

In [18]:
ranarr.min()

7

In [19]:
ranarr.max()

31

In [20]:
ranarr.argmin() # it shows the index of the minimum value

1

In [21]:
ranarr.argmax() # it shows the index of the maximum value

0

In [25]:
arr = np.arange(1,10)

In [26]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr[5] # it shows the value of the 5th index in the array

6

In [28]:
arr[1:6] # it shows the value form the 1st index to 6th index in a Array

array([2, 3, 4, 5, 6])

In [29]:
arr[:6] # it will show the value from default 0 index to 6th index in Array

array([1, 2, 3, 4, 5, 6])

In [30]:
arr[5:] # it will show the values from 5th index to default end of the arry

array([6, 7, 8, 9])

In [31]:
# BROADCASTING

In [32]:
arr = np.arange(1,10,2)

In [33]:
arr

array([1, 3, 5, 7, 9])

In [34]:
arr[0:3] = 10 # it is used to change the original values to 10 from 0 index value to 3rd index value

In [35]:
arr

array([10, 10, 10,  7,  9])

In [36]:
arr[0:2] = 5

In [37]:
arr

array([ 5,  5, 10,  7,  9])

In [38]:
# slice_of_arr

In [39]:
arr = np.arange(1,15,1)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
slice_of_arr = arr[0:5]

In [42]:
slice_of_arr

array([1, 2, 3, 4, 5])

In [43]:
slice_of_arr = arr[2:10]

In [44]:
slice_of_arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
slice_of_arr = arr[5:]

In [46]:
slice_of_arr

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
slice_of_arr [:] = 25 # it is used to change all values of the array to 25

In [48]:
slice_of_arr

array([25, 25, 25, 25, 25, 25, 25, 25, 25])