<a href="https://colab.research.google.com/github/ssp1989/DTC/blob/main/NUMPY(15_12_2022).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = 5
b = 4
c = a+b
print(c)

9


In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.arange(10,250,6)

array([ 10,  16,  22,  28,  34,  40,  46,  52,  58,  64,  70,  76,  82,
        88,  94, 100, 106, 112, 118, 124, 130, 136, 142, 148, 154, 160,
       166, 172, 178, 184, 190, 196, 202, 208, 214, 220, 226, 232, 238,
       244])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.twos(3)

AttributeError: ignored

In [ ]:
np.zeros(5,5)

TypeError: ignored

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linkspace(0,10,3)

AttributeError: ignored

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.eye((2,2))

TypeError: ignored

In [ ]:
np.eye((4,2))

TypeError: ignored

In [ ]:
np.({2,2})

SyntaxError: ignored

In [ ]:
np.random.rand(2)

array([0.87896692, 0.54575763])

In [ ]:
np.random.rand(5)

array([0.92838604, 0.19672675, 0.37860613, 0.7390016 , 0.39709374])

In [ ]:
np.random.rand(10,20)

array([[0.37907605, 0.38678924, 0.43167257, 0.69155021, 0.86474438,
        0.66322718, 0.99669143, 0.30429563, 0.33899039, 0.75291412,
        0.3295875 , 0.21858044, 0.6881362 , 0.91434571, 0.53081789,
        0.98517502, 0.04843219, 0.04279066, 0.80464671, 0.84030414],
       [0.74867676, 0.75034946, 0.89689953, 0.45371239, 0.73347304,
        0.91357295, 0.35425828, 0.65116697, 0.67270324, 0.14072056,
        0.91079604, 0.86200513, 0.54783166, 0.3957601 , 0.51590755,
        0.73141352, 0.40363806, 0.73492918, 0.10147257, 0.73673456],
       [0.68590654, 0.46599888, 0.96611241, 0.5371125 , 0.81906667,
        0.16359372, 0.86440067, 0.69044594, 0.26838122, 0.01551611,
        0.21345343, 0.67867867, 0.45250465, 0.52993494, 0.68304397,
        0.84798276, 0.9038564 , 0.96746236, 0.76639453, 0.23904605],
       [0.90632151, 0.50047239, 0.09347265, 0.28056735, 0.73901036,
        0.08149303, 0.33844311, 0.22901408, 0.69844693, 0.87783704,
        0.50273562, 0.38477298, 0.9692064 , 0

In [ ]:
np.random.rand(5,5)

array([[0.41552977, 0.57520927, 0.69694672, 0.62530181, 0.56738813],
       [0.9126124 , 0.07035192, 0.66547554, 0.68066414, 0.40631549],
       [0.76203918, 0.78868919, 0.44569953, 0.19852375, 0.88008872],
       [0.75666532, 0.63817759, 0.89621045, 0.24594065, 0.67184015],
       [0.20923098, 0.01774239, 0.38236737, 0.194542  , 0.82844282]])

In [ ]:
np.random.randint(1,100)

20

In [ ]:
np.random.randint(5,1000)

592

In [ ]:
np.random.randint(1,100,2)

array([47, 79])

In [ ]:
np.random.randint(1,100,3)

array([18, 74, 93])